  DROP TABLE USER_ACCOUNT CASCADE CONSTRAINTS; --FIRST TO INSERT
  DROP TABLE RULE_DECK CASCADE CONSTRAINTS;    --SECOND TO INSERT
  DROP TABLE GAME_TYPE CASCADE CONSTRAINTS;    --THIRD TO INSERT
  DROP TABLE CARD CASCADE CONSTRAINTS;         --FOURTH TO INSERT
  DROP TABLE RULE_CARD CASCADE CONSTRAINTS;    --FIFTH TO INSERT
  DROP TABLE CARD_MAPPER CASCADE CONSTRAINTS;  --SIXTH TO INSERT
  DROP TABLE DECK CASCADE CONSTRAINTS;         --SEVENTH TO INSERT
  DROP TABLE DECK_CARDLIST CASCADE CONSTRAINTS;--EIGHT TO INSERT
  DROP TABLE GAME_OWNER CASCADE CONSTRAINTS;   --NINTH TO INSERT

  CREATE TABLE USER_ACCOUNT 
   (	"ID" NUMBER NOT NULL ENABLE, 
	"USER_NAME" VARCHAR2(40 BYTE) NOT NULL ENABLE, 
	"PASSWORD" VARCHAR2(40 BYTE) NOT NULL ENABLE, 
	"MAIL_ADDRESS" VARCHAR2(40 BYTE) NOT NULL ENABLE, 
	 CONSTRAINT "USER_ACCOUNT_PK" PRIMARY KEY ("ID"));

    CREATE TABLE RULE_DECK 
   (	"ID" NUMBER NOT NULL ENABLE, 
	"MIN_QUANTITY" NUMBER(3,0) NOT NULL ENABLE, 
	"MAX_QUANTITY" NUMBER(3,0) DEFAULT 999, 
	"STANDARD_CARD_QUANTITY" NUMBER(2,0) NOT NULL ENABLE, 
	 CONSTRAINT "RULE_DECK_PK" PRIMARY KEY ("ID")
   );
   
  CREATE TABLE GAME_TYPE
   (	"ID" NUMBER, 
	"RULE_DECK_ID" NUMBER, 
	"NAME" VARCHAR2(40 BYTE), 
	"SHOR_DESCRIPTION" VARCHAR2(1000 BYTE), 
	"RULE_OF_THE_GAME"VARCHAR2(1000 BYTE), 
	"IS_PUBLIC" NUMBER(1,0),
   CONSTRAINT "GAME_TYPE_PK" PRIMARY KEY ("ID"),
  CONSTRAINT "GAME_TYPE_FK1" FOREIGN KEY ("RULE_DECK_ID") REFERENCES "RULE_DECK" ("ID") ON DELETE CASCADE ENABLE
   ) ;

  CREATE TABLE CARD 
   (	"ID" NUMBER NOT NULL ENABLE, 
	"GAME_TYPE_ID" NUMBER NOT NULL ENABLE , 
	"NAME" VARCHAR2(60 BYTE) NOT NULL ENABLE, 
	"COST" VARCHAR2(40 BYTE) , 
	"DESCRIPTION" VARCHAR2(300 BYTE) , 
	"BATTLE_ATTRIBUTE_1" VARCHAR2(20 BYTE) , 
	"BATTLE_ATTRIBUTE_2" VARCHAR2(20 BYTE) , 
	"FIELD1" VARCHAR2(20 BYTE), 
	"FIELD2" VARCHAR2(20 BYTE), 
	"FIELD3" VARCHAR2(20 BYTE), 
	"FIELD4" VARCHAR2(20 BYTE), 
	"FIELD5" VARCHAR2(20 BYTE), 
  CONSTRAINT "CARD_PK" PRIMARY KEY ("ID"),
  CONSTRAINT "CARD_FK1" FOREIGN KEY ("GAME_TYPE_ID") REFERENCES "GAME_TYPE" ("ID")
  );
  CREATE TABLE RULE_CARD
   (	"ID" NUMBER NOT NULL ENABLE, 
	"ID_CARD" NUMBER NOT NULL ENABLE, 
	"RULE_DECK_ID" NUMBER NOT NULL ENABLE, 
	"MAX_AMOUNT" NUMBER NOT NULL ENABLE, 
	 CONSTRAINT "TABLE1_PK" PRIMARY KEY ("ID"),
	 CONSTRAINT "TABLE1_FK1" FOREIGN KEY ("ID_CARD") REFERENCES "CARD" ("ID"), 
	 CONSTRAINT "TABLE1_FK2" FOREIGN KEY ("RULE_DECK_ID") REFERENCES "RULE_DECK" ("ID") ENABLE
   ) ;

  CREATE TABLE CARD_MAPPER 
   (	"ID" NUMBER NOT NULL ENABLE, 
	"GAME_TYPE_ID" NUMBER,
  "BATTLE_ATTRIBUTE_1" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"BATTLE_ATTRIBUTE_2" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"FIELD1" VARCHAR2(20 BYTE), 
	"FIELD2" VARCHAR2(20 BYTE), 
	"FIELD3" VARCHAR2(20 BYTE), 
	"FIELD4" VARCHAR2(20 BYTE), 
	"FIELD5" VARCHAR2(20 BYTE), 
	 CONSTRAINT "CARD_MAPPER_PK" PRIMARY KEY ("ID"), 
	 CONSTRAINT "CARD_MAPPER_FK1" FOREIGN KEY ("GAME_TYPE_ID") REFERENCES "GAME_TYPE" ("ID") ENABLE
   );
   
     CREATE TABLE DECK 
   (	"ID" NUMBER NOT NULL ENABLE, 
	"USER_ID" NUMBER NOT NULL ENABLE,
	"GAME_TYPE_ID" NUMBER NOT NULL ENABLE, 
	"NAME" VARCHAR2(50 BYTE) NOT NULL ENABLE,
        "IS_PUBLIC" NUMBER DEFAULT 1,
	 CONSTRAINT "DECK_PK" PRIMARY KEY ("ID"), 
	 CONSTRAINT "DECK_FK1" FOREIGN KEY ("USER_ID") REFERENCES "USER_ACCOUNT" ("ID") ENABLE,
	 CONSTRAINT "DECK_FK3" FOREIGN KEY ("GAME_TYPE_ID") REFERENCES "GAME_TYPE" ("ID") 
   ) ;
   
   CREATE TABLE DECK_CARDLIST
   (	"DECK_ID" NUMBER NOT NULL ENABLE, 
	"CARD_ID" NUMBER NOT NULL ENABLE, 
	 CONSTRAINT "DECK_CARDLIST_FK1" FOREIGN KEY ("DECK_ID") REFERENCES "DECK" ("ID") ENABLE, 
	 CONSTRAINT "DECK_CARDLIST_FK2" FOREIGN KEY ("CARD_ID") REFERENCES "CARD" ("ID") ENABLE
   );
   
     CREATE TABLE GAME_OWNER
   (	"GAME_TYPE_ID" NUMBER NOT NULL ENABLE, 
	"USER_ID" NUMBER NOT NULL ENABLE, 
	 CONSTRAINT "GAME_OWNER_FK1" FOREIGN KEY ("GAME_TYPE_ID")
	  REFERENCES "GAME_TYPE" ("ID") ENABLE, 
	 CONSTRAINT "GAME_OWNER_FK2" FOREIGN KEY ("USER_ID")
	  REFERENCES "USER_ACCOUNT" ("ID") ENABLE
   );
